.TH RCHECKBOOK-UPDATE 1 "21 June 2026" "version 0.4"
.SH NAME
rcheckbook-update \- update entry in registry.
.SH SYNOPSIS
rcheckbook update [path/to/database]
--id <id> | -i <id> 
[--date <date> | -d <date>][--check-number <check number>]
[--category <category>]--vendor <vendor>
[--memo <memo> | -m <memo>][--reconciled | -r]
[--not-reconciled]
[--reconciled | -r]
[--transaction_type <type> | -t <type>]
--amount <amount> | -a <amount>
.SH DESCRIPTION
The update subcommand can be used to update an entry 
in the registry with all the data that you know.
.PP
Everything is optional, except for the id, 
Because not everything will be changed.
.PP
If no path to database is given,
the program will try to open a database located in
.B .checkbook
user your home directory named
.B register.db.
.SH OPTIONS
.TP
.B -a <amount>, --amount <amount>
The amount exchanged.
.PP
Unlike the add command, this must be a positive number.
.TP
.B --category <category>
The category to assign to the entry.
.PP
If your category has any spaces, make sure to wrap it up in quotes.
.PP
If no category is named or marked uncaegorized, 
it will be considered Uncategorized.
.PP
If a specified category is not found, 
it will be added to the registry along with the transaction.
.PP
The default categories are as follows:
.RS
.IP
Dining
.IP
Gifts
.IP
Groceries
.IP
Opening Balance
.IP
Recreation
.IP
Subscriptions
.IP
Utilities
.RE
.PP
Categories are case insensitive.
.PP
However, 
the case used when specifying a new category 
will be the case stored in the database.
.PP
To keep things consistent,
it is best to capitialize things as if they were
a title.
.TP
.B --check-number <check number>
The check number associated with the exchange.
.PP
Use this to update the check number.
.TP
.B -d <date>, --date <date>
The date the exchange took place.
.PP
When specifying the date, the expected format is
YYYY-MM-DD.
.TP
.B -m <memo>, --memo <memo>
A brief description of the exchange.
.PP
Use this to update the memo.
.TP
.B --not-reconciled
Mark the transaction as not reconciled.
.TP
.B -r, --reconciled
Mark the transaction as reconciled.
.TP
.B -t <type>, --transaction-type <type>
Set the type of transaction.
.PP
Like importing JSON, this can only be one of two values.
.PP
Unlike adding entries, where type is determined by sign,
this is used in cases where the amount was not wrong,
but the sign used was.
.TP
.B --vendor <vendor>
The vendor/payee in the exchange.
.SH EXAMPLES
Add entry to registry:
.RS
.IP
recheckbook add --vendor Bill 
-m "reimburse for food" -a -20
.RE
.PP
Add reconciled transaction from Jan. 01, 1970:
.RS
.IP
recheckbook add -d 1970-01-01 --vendor "Sam Hill Credit Union" 
-m "Interest Earned" -r -a 0.02
.RE
.PP
Add transaction paid via check:
.RS
.IP
recheckbook add --check-number 1260 --vendor "Velociraptor Entertainment" 
-m "Pay Day" -r -a 50000
.RE
.PP
Add transaction with Category:
.RS
.IP
recheckbook add --vendor "Fake Street Electronics" -m "Head set"
--category Gifts -a -200
.RE
