.TH RCHECKBOOK-IMPORT 1 "20 June 2026" "version 0.5.1"
.SH NAME
rcheckbook-import \- import transactions to registry.
.SH SYNOPSIS
rcheckbook import [path/to/database] 
--input-file <file path> | -i <file path>
.SH DESCRIPTION
Import transactions to registry.
.PP
The import subcommand can be used to import transactions 
to the registry from file
in the following formats:
.RS
.IP
JSON (bcheck)
.IP
QIF
.IP
Excel (xlsx)
.IP
ODS
.IP
TSV
.RE
.PP
The extension determines how the program will parse the file.
.PP
If no extension is provided, nothing will be imported.
.PP
Like the add command, 
if you do not provide a database path,
the program will attempt to open
.B register.db
from the
.B .checkbook
directory in your home folder.
.SH OPTIONS
.TP
.B -i <file path>, --input-file <file path>

The file to import.
.PP
As stated under the
.B DESCRIPTION
section, the file extension determines how the file is parsed.
.PP
If you import an ODS or excel file,
the first line is assumed to 
be a header row and it will be skipped over.
.SH ENVIRONMENT
By default, this program generates a database, 
.B when needed
, from schema file with a particular name located 
in a particular directory.
.PP
On Windows, it will look in the following places in order:
.RS
.IP
the executable's directory
.IP
the current directory
.RE
On macOS, Linux, 
and other Unix-like Operating Systems, it will
look in
.B /usr/local/share/rcheckbook
\.
.PP
If the operating system doesn't have these locations,
such as if you were running NixOS, 
or you cannot write to them, 
you can instead tell it look in a specific 
place by setting
.B REGISTRY_SCHEMA_DIR
\.
.PP
When this is set, 
the program will look for the schema file in that directory
before looking elsewhere.
.SH FILES
There is only one file that is important to the program,
which is
.B register.sql
\.
.PP
This file is typically located in the default places specified
in the 
.B ENVIRONMENT
section.
.PP
This file
.B MUST NOT
be renamed.
.SH EXAMPLES
export registry to JSON:
.RS
.IP
recheckbook export -o transactions.bcheck
.RE
.PP
export registry to QIF:
.RS
.IP
recheckbook export -o transactions.qif
.RE
.PP
export registry to Excel:
.RS
.IP
recheckbook export -o transactions.xlsx
.RE
.PP
export registry to TSV:
.RS
.IP
recheckbook export -o transactions.tsv
.RE
.SH SEE ALSO
rcheckbook-add(1),
rcheckbook-list(1)