.TH RCHECKBOOK-REMOVE 1 "21 June 2026" "version 0.3"
.SH NAME
rcheckbook-remove \- remove transaction from registry.
.SH SYNOPSIS
rcheckbook remove [path/to/database] 
--id <id> | -i <id>
.SH DESCRIPTION
The remove subcommand can be used to delete entries
from the registry.
Like the add command, 
if you do not provide a database path,
the program will attempt to open
.B register.db
from the
.B .checkbook
directory in your home folder.
.SH OPTIONS
.TP
.B -i <id>, --id <id>
The identifer of the transaction to remove
.SH EXAMPLES
export registry to JSON:
.RS
.IP
recheckbook export -o transactions.bcheck
.RE
.PP
export registry to QIF:
.RS
.IP
recheckbook export -o transactions.qif
.RE
.PP
export registry to Excel:
.RS
.IP
recheckbook export -o transactions.xlsx
.RE
.PP
export registry to TSV:
.RS
.IP
recheckbook export -o transactions.tsv
.RE
.SH SEE ALSO
rcheckbook-add(1),
rcheckbook-list(1)