.TH RCHECKBOOK-REMOVE 1 "21 June 2026" "version 0.3"
.SH NAME
rcheckbook-remove \- remove transaction from registry.
.SH SYNOPSIS
rcheckbook remove [path/to/database] 
--id <id> | -i <id>
.SH DESCRIPTION
The remove subcommand can be used to delete entries
from the registry.
Like the add command, 
if you do not provide a database path,
the program will attempt to open
.B register.db
from the
.B .checkbook
directory in your home folder.
.SH OPTIONS
.TP
.B -i <id>, --id <id>
The identifer of the transaction to remove.
.PP
the identifier can be found via the list command and
is case insensitive.
.SH EXAMPLES
remove entry with ID FF04C3DC-F0FE-472E-8737-0F4034C049F0:
.RS
.IP
recheckbook remove -i FF04C3DC-F0FE-472E-8737-0F4034C049F0
.RE
.SH SEE ALSO
rcheckbook-add(1),
rcheckbook-list(1)