[package]
name = "rcheckbook"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcheck = "0.2"
shellexpand = "2.1"