[package]
name = "rcheckbook"
authors = ["Bryce Campbell <tonyhawk2100@gmail.com>"]
version = "0.2.2"
edition = "2018"
license = "MIT"
description = "CLI program that can read and write bcheck files."
homepage = "https://github.com/bryceac/rcheckbook"
readme = "README.mediawiki"
repository = "https://github.com/bryceac/rcheckbook"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcheck = "0.3"
shellexpand = "3.1.0"
clap = "4.4.8"